### PR TITLE
escape_and_echo is now used to correctly output the validator_key

### PR DESCRIPTION
**Pull request by mprahl**
I had an issue where the validator_key was not being outputted to a file. This fixes that issue.

### CODE REVIEW

**Comment by mprahl** [comment]
@juliandunn any movement on this? I'd like to delete my fork.

**Comment by juliandunn** [comment]
hey, I don't really monitor this repo. happy to take the PR but where does this method come from?

**Comment by mprahl** [comment]
@juliandunn, it was just one of the built in ones:
http://www.rubydoc.info/gems/knife-windows/0.5.10/Chef/Knife/Core/WindowsBootstrapContext:escape_and_echo

**Comment by mprahl** [comment]
@juliandunn any news?

**Comment by juliandunn** [comment]
whoops! got lost in the noise. merging.

**Pull request merged**
